# Данный workflow компилирует движок на разных платформах

# Отображаемое имя workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: CI/CD

# Запускается при push и PR. Также можно запустить вручную
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
on: [push, pull_request, workflow_dispatch]

jobs:

  # Идентификатор job
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_id
  windows-VS:

    # Отображаемое имя job 
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idname
    name: 🔲 VS

    # Будет запущен на виртуальной машине с последней версией Windows
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # Установленный софт: https://github.com/actions/virtual-environments#available-environments
    runs-on: windows-latest

    # При помощи матриц минимизируем код данного workflow
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        # Переменная CMAKE_GENERATOR_PLATFORM будет иметь значения Win32 и x64
        # https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html#platform-selection
        CMAKE_GENERATOR_PLATFORM: [Win32, x64]
        # Переменная config будет иметь значения Debug и Release
        # Сборка проекта: https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project
        config: [Debug, Release]

    # Последовательность задач
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
    - name: Работаем # Отображаемое имя step
      run: |
        # Скачиваем текущий репозиторий в папку dviglo-repo
        git clone https://github.com/Dviglo/Dviglo dviglo-repo
        # Показываем версию CMake
        cmake --version
        # Создаём проект в папке dviglo-build
        # Visual Studio Generators: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#id5
        cmake dviglo-repo -B dviglo-build -G "Visual Studio 16 2019" -A ${{matrix.CMAKE_GENERATOR_PLATFORM}}
        # Компилируем
        cmake --build dviglo-build --config ${{matrix.config}}

  windows-mingw-w64:

    name: 🔲 mingw-w64
    runs-on: windows-latest

    strategy:
      matrix:
        bits: [32, 64]
        # Переменная CMAKE_BUILD_TYPE будет иметь значения Debug и Release
        # https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
        CMAKE_BUILD_TYPE: [Debug, Release]

    steps:
    - name: Работаем
      shell: cmd
      run: |
        set "PATH=c:\msys64\mingw${{matrix.bits}}\bin;%PATH%"
        git clone https://github.com/Dviglo/Dviglo dviglo-repo
        cmake --version
        g++ --version
        cmake dviglo-repo -B dviglo-build -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=${{matrix.cmake_build_type}}
        cmake --build dviglo-build

  linux-GCC:

    name: 🐧 GCC
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CMAKE_BUILD_TYPE: [Debug, Release]
        URHO3D_64BIT: ["", "-D URHO3D_64BIT=1"]

    steps:

    - name: Устанавливаем софт
      run: |
        # Приложение Doxygen генерирует документацию
        sudo apt-get install -y doxygen
        # Устанавливаем библиотеки, необходимые для компиляции движка
        sudo apt-get install freeglut3-dev

    - name: Работаем
      run: |
        git clone https://github.com/Dviglo/Dviglo dviglo-repo
        cmake --version
        g++ --version
        cmake dviglo-repo -B dviglo-build -D CMAKE_BUILD_TYPE=${{matrix.CMAKE_BUILD_TYPE}} ${{matrix.URHO3D_64BIT}}
        cmake --build dviglo-build

  linux-Clang:

    name: 🐧 Clang
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CMAKE_BUILD_TYPE: [Debug, Release]
        URHO3D_64BIT: ["", "-D URHO3D_64BIT=1"]

    steps:

    - name: Устанавливаем софт
      run: |
        sudo apt-get install -y doxygen
        sudo apt-get install freeglut3-dev

    - name: Работаем
      run: |
        git clone https://github.com/Dviglo/Dviglo dviglo-repo
        cmake --version
        export CC=clang
        export CXX=clang++
        clang++ --version
        cmake dviglo-repo -B dviglo-build -D CMAKE_BUILD_TYPE=${{matrix.CMAKE_BUILD_TYPE}} ${{matrix.URHO3D_64BIT}}
        cmake --build dviglo-build
