# Данный workflow конвертирует документацию из Markdown в HTML и публикует её на сайте.
# Про токен DVIGLO_SITE_TOKEN читайте тут: https://dviglo.github.io/MarkdownDocs/Git/GitHub%20Actions.md.html

# Отображаемое имя workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: Markdown > HTML

on:
  # Запускается, если в ветке master в папке Docs/Markdown были изменения
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
  push:
    branches:
    - master
    paths:
    - Docs/Markdown/**

  # Также можно запустить вручную
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch:

jobs:
  # Идентификатор job
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_id
  Konvertaciya:
    # Будет запущен на виртуальной машине с последней версией Ubuntu
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # Отображаемое имя job 
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idname
    name: Markdown > HTML

    # Последовательность задач
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:

    - name: Markdown > HTML # Отображаемое имя step

      run: |
        # Скачиваем текущий репозиторий в папку DvigloRepo
        git clone https://github.com/Dviglo/Dviglo DvigloRepo

        # Скачиваем исходники конвертора в папку ConvRepo
        git clone https://github.com/Dviglo/md2html ConvRepo

        # Создаём проект в папке ConvBuild
        cmake ConvRepo -B ConvBuild

        # Компилируем. Скомпилированная программа будет помещена в папку ConvBuild/Result
        cmake --build ConvBuild

        # Конвертируем Markdown в HTML. Результат будет помен в папку MarkdownDocs
        ./ConvBuild/Result/md2html DvigloRepo/Docs/Markdown MarkdownDocs

        # Качаем репозиторий сайта в папку SiteRepo.
        # Так как используется токен, то будут иметься права на запись в этот репозиторий
        git clone "https://${{ secrets.DVIGLO_SITE_TOKEN }}@github.com/Dviglo/dviglo.github.io" SiteRepo

        # Удаляем директорию, если существует
        rm -rf SiteRepo/MarkdownDocs

        # Копируем папку MarkdownDocs в папку SiteRepo
        cp -R MarkdownDocs SiteRepo

        # Копируем содержимое папки с ресурсами
        cp -R ConvRepo/___res/. SiteRepo/MarkdownDocs/___res

        # Копируем аддон, создающий боковую панель сайта
        cp -R DvigloRepo/Docs/Addon.js SiteRepo/MarkdownDocs/___res

        # Автор коммита
        git config --global user.email "dviglo[bot]@users.noreply.github.com"
        git config --global user.name "Dviglo[bot]"

        # Отправляем изменения в репозиторий сайта
        cd SiteRepo
        git add -A
        git diff-index --quiet HEAD || git commit -m "Обновление MarkdownDocs" # Создаём коммит, только если есть изменения
        git push origin master
