# Данный workflow закрывает заброшенные issues и pull requests

# Отображаемое имя workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name
name: Закрытие заброшенных issues и pull requests

on:
  # Запускается каждый день в 2:15 UTC
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
    - cron: "15 2 * * *"

  # Также можно запустить вручную
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch:

jobs:
  # Идентификатор job
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_id
  Zabrosheno:

    # Будет запущен на виртуальной машине с последней версией Ubuntu
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # Отображаемое имя job 
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idname
    name: Заброшено

    # Последовательность задач
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:

      # Первая (и единственная) задача
    - name: Запускаем скрипт actions/stale@v3 # Отображаемое имя step
      uses: actions/stale@v3 # Исходник скрипта можно посмотреть тут: https://github.com/actions/stale
      with: # Параметры скрипта
        days-before-stale: 30 # Дней перед напоминанием
        days-before-close: 15 # Дней перед закрытием
        stale-issue-message: | # Сообщение при напоминании
          Эта issue помечена как заброшенная, так как здесь не было активности 30 дней.
          Если активности не будет еще 15 дней, она будет закрыта.
        stale-pr-message: | # Сообщение при закрытии
          Этот pull request помечен как заброшенный, так как здесь не было активности 30 дней.
          Если активности не будет еще 15 дней, он будет закрыт.
        stale-issue-label: "заброшено" # Метка будет установлена при напоминании о заброшенной issue
        stale-pr-label: "заброшено" # Метка будет установлена при напоминании о заброшенном pull request
        exempt-issue-labels: "не заброшено" # Issues с такой меткой будут проигнорированы
        exempt-pr-labels: "не заброшено" # Pull requests с такой меткой будут проигнорированы
